# Generated by Django 4.2.5 on 2025-01-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktg_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
